# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e89eb7c699ae7221a515c6972d45102aa6299bbd4eaf51130d94668041ed779545f7e7e0ef5428d7edca69ec567938b09829647dab52ea3f54fc3efe96a0e43e

test:
  secret_key_base: 10b568729f9ba94b02501276d451dc25a2245866698d6f60dca7fc7b0bb9fe0c1533bb6cb60c6d1e1c46469602c60b9bc49ee46f76a75894ecd2b31fa9ce7bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
